spring:
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://192.9.51.175:3306/spring_cache
    url: jdbc:mysql://localhost:3306/springboot
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
     # 是否启用模板缓存。
     cache: true
     # 是否检查模板位置是否存在。
     check-template: true
     # 是否为Web框架启用Thymeleaf视图分辨率。
     enabled: true
     # 编码格式, 默认UTF-8
     encoding: UTF-8
     # 应用于模板的模板模式。另请参阅Thymeleaf的TemplateMode枚举。
     mode: HTML
     # 后缀 默认 .html
     suffix: .html
     # 模板文件存放位置  , 默认 classpath:/templates/
     prefix: classpath:/templates/
  redis:
    host: 192.168.1.106
  rabbitmq:
    host: 192.168.1.106

  elasticsearch:
    jest:
      uris: http://192.168.1.106:9200/
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.106:9300



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml









